name: Deploy Web Platform

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

     # =====================
      # GET RUNNER IP
      # =====================
      - name: Get Runner IP
        run: |
          echo "MY_IP=$(curl -s https://ifconfig.me)/32" >> $GITHUB_ENV  
          
      # ===================== 
      # SETUP TERRAFORM
      # ===================== 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0" # O la versión que uses    

     # ===================== 
     # AWS CREDENTIALS 
     # =====================    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # =====================
      # TERRAFORM INIT
      # =====================
      - name: Terraform Init
        working-directory: ./iac
        run: terraform init     

      # =====================
      # TERRAFORM APPLY
      # =====================
      - name: Terraform Apply
        working-directory: ./iac
        run: |
          terraform apply -auto-approve \
          -var="my_ip=['${{ env.MY_IP }}']" \
          -var="ssh_public_key=${{ vars.SSH_PUBLIC_KEY }}"

      # =====================
      # GET IP HOST & ECR
      # =====================  
      - name: Get Terraform Outputs
        working-directory: ./iac
        run: |
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
          # Extraemos solo el dominio del ECR (sin el nombre del repo)
          echo "ECR_REGISTRY=$(terraform output -raw ecr_repository_url | cut -d'/' -f1)" >> $GITHUB_ENV
          echo "SG_ID=$(terraform output -raw security_group_id)" >> $GITHUB_ENV


      # =====================
      # AUTHORIZE RUNNER
      # =====================
      - name: Allow SSH from runner
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr $MY_IP

      # =====================
      # BUILD & PUSH TO ECR
      # =====================

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push images
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/nextcloud-app:latest ./services/nextcloud
          # CAMBIO: Usar el nombre que espera el docker-compose (nextcloud-nginx)
          docker build -t ${{ env.ECR_REGISTRY }}/nextcloud-nginx:latest ./services/nginx
          docker push ${{ env.ECR_REGISTRY }}/nextcloud-app:latest
          docker push ${{ env.ECR_REGISTRY }}/nextcloud-nginx:latest

      # =====================
      # COPY CODE
      # =====================
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/Web_Platform"

      # =====================
      # CREATE .ENV
      # =====================
      - name: Create env file on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Web_Platform/docker

            cat <<EOF > .env
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            NEXTCLOUD_ADMIN_USER=${{ secrets.NEXTCLOUD_ADMIN_USER }}
            NEXTCLOUD_ADMIN_PASSWORD=${{ secrets.NEXTCLOUD_ADMIN_PASSWORD }}
            ECR_REGISTRY=${{ env.ECR_REGISTRY }}
            EOF

      # =====================
      # DEPLOY
      # =====================
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ir a la carpeta raíz del proyecto
            cd /home/ubuntu/Web_Platform
            # Dar permisos a todo el contenido de scripts
            chmod +x scripts/*.sh
            # Ejecutar el deploy desde la raíz
            ./scripts/deploy.sh         